# Generated by Django 5.0.8 on 2025-03-13 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="MessageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="chats.message",
                    ),
                ),
            ],
        ),
    ]
